### ISSUE TITLE
zegary od e60

### ISSUE THREAD

**Issue by Dreed420** [Marcin648/e90-dashboard-ets2#5]
Witajcie, zaprogramowalem arduino nano waszym softem lecz zmienilem biblioteke na aktualniejsza poniewaz była tam obsługa oscylatora 8mhz - po dodaniu pluginu - mam taki oto komunikat

[2022-08-05 01:31:14,363] INFO - Game successfully loaded
[2022-08-05 01:31:14,409] WARN - System.MissingMethodException: Method not found: 'Int32 GameReaderCommon.StatusDataBase.get_EngineIgnitionOn()'.
   at E90DashboardSimhub.E90Dashboard.DataUpdate(PluginManager pluginManager, GameData& data)
   at SimHub.Plugins.PluginManager.manager_DataUpdated(GameData data, IGameManager manager)
[2022-08-05 01:31:15,984] WARN - System.MissingMethodException: Method not found: 'Int32 GameReaderCommon.StatusDataBase.get_EngineIgnitionOn()'.
   at E90DashboardSimhub.E90Dashboard.DataUpdate(PluginManager pluginManager, GameData& data)
   at SimHub.Plugins.PluginManager.manager_DataUpdated(GameData data, IGameManager manager)

Moje pytanie czy zegary od e60 są w ogole wspierane? Z gory dziekuje za odpowiedz i pozdrawiam

**Comment by Marcin648** [comment]
Cześć! Nie jestem w stanie stwierdzić czy zegary od e60 zadziałają. Bazowałem na kodach CAN z tej strony http://www.loopybunny.co.uk/CarPC/k_can.html jeśli w e60 są takie same, to powinno działać. Niestety w niektórych wariantach zegarów z tytułowego e90 występują pewne problemy.
Błąd, który masz sugeruje mi, że gra, którą próbujesz uruchomić, nie obsługuje informacji o włączonym silniku. Nie jestem tego pewien, może też w nowej wersji SimHUB'a coś się zmieniło. Plugin rzeczywiście nie uruchomi zegarow jeśli nie dostanie tego sygnału [E90Dashboard.cs#L19](https://github.com/Marcin648/E90DashboardSimhub/blob/6f1433f231bf48f1c304b1bce8b78423c8150762/Marcin648.e90DashboardSimhub/E90Dashboard.cs#L19) 

Też jestem świadomy, że aktualnie używana biblioteka CAN ma pewne wady, chciałem ją wymienić na https://github.com/autowp/arduino-mcp2515 
Jeśli masz inną propozycję, pisz śmiało. :)

**Comment by vejinnovem** [comment]
Dreed420 będziesz miał zamiar podzielić się swoim szkicem? Mam anglika z e90. Celuję w SimHuba, a nie mogę nawet zmusić licznika do ruszenia.
Wciąż mruga ikonką samochodu na podnośniku.
To co wynalazłem w sieci to jakieś kody z błędami z tematów na forach, na które nikt nie odpowiedział i nie daję rady na własną rękę zmusić tego do działania.
Projekt Marcina mi nie pomoże, bo wymaga od razu arduino mega, a ja mam tylko leonardo i platformio się wiesza przy próbie wgrania firmware'u.

**Comment by Marcin648** [comment]
@vejinnovem Cześć! Ikonka na podkowniku to zwykle błąd na magistrali canbus. Też tak miałem na początku, rozwiązaniem okazało się odłączenie rezystora terminującego na płytce modułu canbus. Wiem, że to nieintuicyjne, bo według specyfikacji ten rezystor tam powinien być, ale podziałało i kilku innym osobom również. Na płytce Seeed Studio robi się to poprzez przecięcie pola stykowego oznaczonego jako P1 pod płytką.

Arduino Mega nie jest wymagane, zostało użyte tylko dlatego, że je miałem pod ręką. Robiłem testy na najtańszym zestawie Arduino Nano + tania płytka MCP2515 i działało dobrze. Jedyne wymagało to zmiany zegara biblioteki, bo ta tańsza płytka działa na 8MHz, a nie 16Mhz.
Aby kompilować w platform.io do innych płytek, starczy dopisać je do platformio.ini.
Lista płytek z przykładami: https://docs.platformio.org/en/latest/boards/index.html

Do zegarów nie mam aktualnie dostepu, ale postaram się w wolnym czasie przepisać ten projekt na bardziej przyjazny i wykorzystać nowszą bibliotekę.

**Comment by vejinnovem** [comment]
W pewnym momencie mi się udało, a przynajmniej nie zwróciło mi żadnego błędu, wybrałem płytkę, wgrałem kod.
Nie mam zielonego pojęcia gdzie wrzucić dll, więc wrzuciłem go wszędzie. (ale w domyśle tam, gdzie binarka, wrzuciłem zarówno do x86 jak i do x64).
Program od telemetrii łączy się z Arduino, ale nie chce się połączyć z telemetrią na 127.0.0.1. Niby host od razu odrzuca połączenie.
Licznik cały czas pokazuje ikonkę samochodu na podnośniku.
Mam płytkę MCP2515. Przynajmniej tak zapamiętałem nazwę. Na pewno coś tam robi, bo bez niej nie ma ikonki podnośnika.
Możesz mnie nakierować, gdzie zmienić ten zegar? Nie mam żadnego innego arduino pod ręką.
I jeśli ta tania płytka też wymaga wywalenia rezystora, to możesz nakierować mnie, który to? Na mojej płytce są dwa rezystory.

**Comment by Dreed420** [comment]
MCP2515 posiada punkt J1 - tam montuje sie zworke aby byl aktywny rezystor 120k z tego co pamietam.
Plugin (dll) wrzucasz do folderu gdzie jest zainstalowany simhub - glowny folder - wtedy pojawi ci sie w simhub aditional plugins u gory e90 dashboard

**Comment by vejinnovem** [comment]
Odlutowałem R1 i wtedy płytka nie chciała działać. Odlutowałem R2 i zero różnicy, dalej biedne BMW na podnośniku.
J1 zwierałem i rozwierałem, ale bez różnicy. 
Zegary jakby pstrykają kiedy jest aktywny inny kod, ostatni stąd:
https://forum.arduino.cc/t/controlling-bmw-e90-instrument-cluster/670728
Pstrykają wtedy, gdy uruchamiam monitor portu szeregowego, choć nie zawsze.
Lub wtedy gdy ten kod jest aktywny, a nadpisuję go tym samym kodem.
Poza podnośnikiem i pstrykaniem na ułamek sekundy zegarami nie udało mi się gnoja zmusić do działania.

**Comment by Dreed420** [comment]
@vejinnovem masz discorda? - wroce ze spaceru z psami to podzialamy razem
Dreed#7529 - dodaj lub odezwij sie

**Comment by vejinnovem** [comment]
Chociaż to totalny offtop, no ale nie chciałem zasyfiać issuesów polskimi tematami, no a jednak wygodniej po swojemu narzekać na pasmo niepowodzeń, to dopiszę tylko że ten plugin w simhub udało mi się odpalić, ale ma totalnie w głębokim poważaniu polecenia connect. Podłącza się totalnie bez weryfikacji, nawet jak dam fizyczny port szeregowy COM1 to się łączy, a po chwili zupełnie z niczym się nie chce połączyc i nie reaguje w ogóle na connect.
Jedynie raz udało mi się zrobić connect i zegary pstryknęły, pokazał się podnośnik, ale zanim mi się odpaliła gra, wcisnąłem alt-tab, to już nie było połączone.

**Comment by Dreed420** [comment]
> @vejinnovem Cześć! Ikonka na podkowniku to zwykle błąd na magistrali canbus. Też tak miałem na początku, rozwiązaniem okazało się odłączenie rezystora terminującego na płytce modułu canbus. Wiem, że to nieintuicyjne, bo według specyfikacji ten rezystor tam powinien być, ale podziałało i kilku innym osobom również. Na płytce Seeed Studio robi się to poprzez przecięcie pola stykowego oznaczonego jako P1 pod płytką.
> 
> Arduino Mega nie jest wymagane, zostało użyte tylko dlatego, że je miałem pod ręką. Robiłem testy na najtańszym zestawie Arduino Nano + tania płytka MCP2515 i działało dobrze. Jedyne wymagało to zmiany zegara biblioteki, bo ta tańsza płytka działa na 8MHz, a nie 16Mhz. Aby kompilować w platform.io do innych płytek, starczy dopisać je do platformio.ini. Lista płytek z przykładami: https://docs.platformio.org/en/latest/boards/index.html
> 
> Do zegarów nie mam aktualnie dostepu, ale postaram się w wolnym czasie przepisać ten projekt na bardziej przyjazny i wykorzystać nowszą bibliotekę.

Jest szansa na tą nowszą blibliotekę? :)

**Comment by Marcin648** [comment]
@Dreed420 Mogę zdradzić, że za kulisami powstaje projekt, który będzie obsługiwał większą ilość zegarów i wszystko będzie się dało skonfigurować w jednym pliku. Niestety dużo pracy jeszcze trzeba w to włożyć. :)

**Comment by Dreed420** [comment]
Chętnie się pisze do pomocy ;) mam parę zegarów więc zawsze mogę coś
potestowac

niedz., 9 kwi 2023, 12:54 użytkownik Marcin Jakubowski <
***@***.***> napisał:
